
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'CardListsCole': typeof import("../components/CardListsCole.vue")['default']
    'CardListsEvan': typeof import("../components/CardListsEvan.vue")['default']
    'Companies': typeof import("../components/Companies.vue")['default']
    'CourseCard copy': typeof import("../components/CourseCard copy.vue")['default']
    'CourseCard': typeof import("../components/CourseCard.vue")['default']
    'CourseContent': typeof import("../components/CourseContent.vue")['default']
    'CourseDescription': typeof import("../components/CourseDescription.vue")['default']
    'CourseInfoCard': typeof import("../components/CourseInfoCard.vue")['default']
    'ExploreSkills': typeof import("../components/ExploreSkills.vue")['default']
    'FeaturedReview': typeof import("../components/FeaturedReview.vue")['default']
    'FrequentlyBoughtTogether': typeof import("../components/FrequentlyBoughtTogether.vue")['default']
    'Header': typeof import("../components/Header.vue")['default']
    'HeroSection': typeof import("../components/HeroSection.vue")['default']
    'InstructorCard': typeof import("../components/InstructorCard.vue")['default']
    'RequirementDescription': typeof import("../components/RequirementDescription.vue")['default']
    'ReviewCard': typeof import("../components/ReviewCard.vue")['default']
    'Reviews': typeof import("../components/Reviews.vue")['default']
    'StudentsAlsoBought': typeof import("../components/StudentsAlsoBought.vue")['default']
    'WhatYouLearn': typeof import("../components/WhatYouLearn.vue")['default']
    'NuxtWelcome': typeof import("../../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../../../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../../../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
    'NoScript': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCardListsCole': typeof import("../components/CardListsCole.vue")['default']
    'LazyCardListsEvan': typeof import("../components/CardListsEvan.vue")['default']
    'LazyCompanies': typeof import("../components/Companies.vue")['default']
    'LazyCourseCard copy': typeof import("../components/CourseCard copy.vue")['default']
    'LazyCourseCard': typeof import("../components/CourseCard.vue")['default']
    'LazyCourseContent': typeof import("../components/CourseContent.vue")['default']
    'LazyCourseDescription': typeof import("../components/CourseDescription.vue")['default']
    'LazyCourseInfoCard': typeof import("../components/CourseInfoCard.vue")['default']
    'LazyExploreSkills': typeof import("../components/ExploreSkills.vue")['default']
    'LazyFeaturedReview': typeof import("../components/FeaturedReview.vue")['default']
    'LazyFrequentlyBoughtTogether': typeof import("../components/FrequentlyBoughtTogether.vue")['default']
    'LazyHeader': typeof import("../components/Header.vue")['default']
    'LazyHeroSection': typeof import("../components/HeroSection.vue")['default']
    'LazyInstructorCard': typeof import("../components/InstructorCard.vue")['default']
    'LazyRequirementDescription': typeof import("../components/RequirementDescription.vue")['default']
    'LazyReviewCard': typeof import("../components/ReviewCard.vue")['default']
    'LazyReviews': typeof import("../components/Reviews.vue")['default']
    'LazyStudentsAlsoBought': typeof import("../components/StudentsAlsoBought.vue")['default']
    'LazyWhatYouLearn': typeof import("../components/WhatYouLearn.vue")['default']
    'LazyNuxtWelcome': typeof import("../../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../../../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../../../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
    'LazyNoScript': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CardListsCole: typeof import("../components/CardListsCole.vue")['default']
export const CardListsEvan: typeof import("../components/CardListsEvan.vue")['default']
export const Companies: typeof import("../components/Companies.vue")['default']
export const CourseCard copy: typeof import("../components/CourseCard copy.vue")['default']
export const CourseCard: typeof import("../components/CourseCard.vue")['default']
export const CourseContent: typeof import("../components/CourseContent.vue")['default']
export const CourseDescription: typeof import("../components/CourseDescription.vue")['default']
export const CourseInfoCard: typeof import("../components/CourseInfoCard.vue")['default']
export const ExploreSkills: typeof import("../components/ExploreSkills.vue")['default']
export const FeaturedReview: typeof import("../components/FeaturedReview.vue")['default']
export const FrequentlyBoughtTogether: typeof import("../components/FrequentlyBoughtTogether.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const HeroSection: typeof import("../components/HeroSection.vue")['default']
export const InstructorCard: typeof import("../components/InstructorCard.vue")['default']
export const RequirementDescription: typeof import("../components/RequirementDescription.vue")['default']
export const ReviewCard: typeof import("../components/ReviewCard.vue")['default']
export const Reviews: typeof import("../components/Reviews.vue")['default']
export const StudentsAlsoBought: typeof import("../components/StudentsAlsoBought.vue")['default']
export const WhatYouLearn: typeof import("../components/WhatYouLearn.vue")['default']
export const NuxtWelcome: typeof import("../../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../../../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
export const NoScript: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCardListsCole: typeof import("../components/CardListsCole.vue")['default']
export const LazyCardListsEvan: typeof import("../components/CardListsEvan.vue")['default']
export const LazyCompanies: typeof import("../components/Companies.vue")['default']
export const LazyCourseCard copy: typeof import("../components/CourseCard copy.vue")['default']
export const LazyCourseCard: typeof import("../components/CourseCard.vue")['default']
export const LazyCourseContent: typeof import("../components/CourseContent.vue")['default']
export const LazyCourseDescription: typeof import("../components/CourseDescription.vue")['default']
export const LazyCourseInfoCard: typeof import("../components/CourseInfoCard.vue")['default']
export const LazyExploreSkills: typeof import("../components/ExploreSkills.vue")['default']
export const LazyFeaturedReview: typeof import("../components/FeaturedReview.vue")['default']
export const LazyFrequentlyBoughtTogether: typeof import("../components/FrequentlyBoughtTogether.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyHeroSection: typeof import("../components/HeroSection.vue")['default']
export const LazyInstructorCard: typeof import("../components/InstructorCard.vue")['default']
export const LazyRequirementDescription: typeof import("../components/RequirementDescription.vue")['default']
export const LazyReviewCard: typeof import("../components/ReviewCard.vue")['default']
export const LazyReviews: typeof import("../components/Reviews.vue")['default']
export const LazyStudentsAlsoBought: typeof import("../components/StudentsAlsoBought.vue")['default']
export const LazyWhatYouLearn: typeof import("../components/WhatYouLearn.vue")['default']
export const LazyNuxtWelcome: typeof import("../../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../../../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../../../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
export const LazyNoScript: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../../../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
